---
name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: always
  RUSTUP_TOOLCHAIN: nightly-2024-12-14

jobs:
  quality-checks-and-build-ubuntu:
    name: ✨ Quality Checks & Build (Ubuntu)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache cargo dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/git
            ~/.cargo/registry
            target
          key: ${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-build-
      - uses: ./.github/actions/ubuntu
      - name: pin
        run: rustup override set ${RUSTUP_TOOLCHAIN}
      - name: Install tools
        run: cargo install taplo-cli --locked
      - name: Build project
        run: cargo build --locked --workspace
      - name: Run quality checks
        run: |
          taplo format --check --config taplo.toml
          cargo fmt --all -- --check
          SKIP_WASM_BUILD=1 cargo clippy --locked --workspace
          SKIP_WASM_BUILD=1 cargo doc --locked --workspace --no-deps
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-build-artifacts
          path: target
      - name: Save cache key
        if: always()
        run: echo "${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}" > cache-key-ubuntu.txt
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cache-key-ubuntu
          path: cache-key-ubuntu.txt

  build-and-test-macos:
    name: 🍏 Build & Test (macOS)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache cargo dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/git
            ~/.cargo/registry
            target
          key: ${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-build-
      - uses: ./.github/actions/macos
      - name: pin
        run: rustup override set ${RUSTUP_TOOLCHAIN}
      - name: Build and Test
        run: |
          cargo build --locked --workspace
          SKIP_WASM_BUILD=1 cargo test --locked --workspace
      - name: Save cache key
        if: always()
        run: echo "${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}" > cache-key-macos.txt
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cache-key-macos
          path: cache-key-macos.txt

  tests-on-cache:
    name: 🧪 Tests (on Ubuntu Cache)
    runs-on: ubuntu-latest
    needs: quality-checks-and-build-ubuntu
    steps:
      - uses: actions/checkout@v4
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: ubuntu-build-artifacts
          path: .
      - name: Install nextest
        run: cargo install cargo-nextest --locked
      - name: pin
        run: rustup override set ${RUSTUP_TOOLCHAIN}
      - name: Run tests
        run: SKIP_WASM_BUILD=1 cargo nextest run --locked --workspace

  cleanup-cache:
    name: 🧹 Cleanup Cache
    runs-on: ubuntu-latest
    needs: [quality-checks-and-build-ubuntu, build-and-test-macos, tests-on-cache]
    if: always()
    steps:
      - name: Download all cache key artifacts
        uses: actions/download-artifact@v4
        with:
          path: cache-keys
      - name: Cleanup build cache
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Deleting caches..."
          find cache-keys -type f -name "*.txt" -print0 | xargs -0 cat | sort -u | while read -r cache_key; do
            echo "Attempting to delete cache with key: $cache_key"
            gh cache delete "$cache_key" --repo ${{ github.repository }} --confirm || echo "Could not delete cache with key $cache_key. It might have already been deleted or not found."
          done
